# This example uses YAML anchors which allows reuse of multiple keys
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
# for a more complex example.
keys:
  - &efim age1ets7cgysvpl7a9grya62ddnpy5v3qk2kmxeysgnzvanx7ugzse5qaq4x9z
  - &pythia age1utvxcqrefpp2d4wgsd26m786cpq94hy4pjumddlecudqqg0qkvsscj4s0r
  - &niobe age15htmcxm4ya7ru9xkxy5tlwytm4543vzd8lpys3rza7vpcsf73stqpfqu56
  - &morpheus age1wzmdqwjjq8u5far3dcjdkwlama39nlfwm8y0mnu7px0lun36lvuqe35cew
  - &franzk age19vkjfrlv8mnxql6g099r7arx0ncl8mc69upjnhqdaw2ahwkgc3ysrwm0yl
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
    - age:
      - *efim
      - *pythia
      - *niobe
      - *morpheus
      - *franzk
  - path_regex: machines/franzk/secrets.yaml$
    key_groups:
    - age:
      - *efim
      - *franzk
