# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/5af7ce5e-88d9-4646-b3cb-f7a762d059b0";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/9f436ec6-6c53-49c0-b198-9807c06e2c19";

  swapDevices =
    [ { device = "/dev/disk/by-uuid/c9f0b726-fab9-4c37-bfbe-c1dd2b7ed04f"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
